// <auto-generated />
namespace RainEqualsOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreatedaStockModelandUpdatedIdentityModelswithDbSetStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatedaStockModelandUpdatedIdentityModelswithDbSetStock));
        
        string IMigrationMetadata.Id
        {
            get { return "201710022002135_Created a StockModel and Updated IdentityModels with DbSet Stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
