// <auto-generated />
namespace RainEqualsOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeletedInventoryModelAddedInventoryModelagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedInventoryModelAddedInventoryModelagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201710030023305_Deleted Inventory.Model,  Added Inventory.Model again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
